spring.application.name=SpringBootRestTest2


spring.datasource.url=jdbc:postgresql://localhost:5433/abesdb2
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=newpassword

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

# SQL Specific rules
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8081

springdoc.swagger-ui.path=/swagger-ui.html